### ISSUE TITLE
Seems like new patch messed up data for doublexp.net 

### ISSUE THREAD

**Issue by Yalme** [rolfosian/drgmissions#1]
After last patch missions info is not correct. I usually used website to find XP missions and it was perfect, but now when I open mission control I don't see same missions and modifiers as on website.
For example, here is screenshots of Azure Weald on website and in the game at the same time:

![Снимок экрана 2023-11-20 181010](https://github.com/rolfosian/drgmissions/assets/25433231/e032098a-406d-49bc-9d41-ad76ddf0e237)
![Снимок экрана 2023-11-20 181018](https://github.com/rolfosian/drgmissions/assets/25433231/ee601cc7-460a-412d-894b-a39f01ead2fa)

Hope you can fix it, and thank you for awesome side tool for this cool game =)

ROCK AND STONE! 💎⛏🐜

**Comment by rolfosian** [comment]
Been meaning to run the BulkMissions script again since the patch but didn't get around to it until now. I've updated the flask server with the new json that will last until either March 2024 or if GSG messes with the mission generator again before then. The new metadata was scraped with the season 4 content box unticked - I don't really feel like refactoring to handle two different sets of data especially as I've personally burnt out on DRG and rarely play it anymore.
