### ISSUE TITLE
API

### ISSUE THREAD

**Issue by utkuvrs** [rolfosian/drgmissions#10]
Hey sorry, you don't have any contact information on your GitHub account so I made an issue.

If I understood correctly, you are hosting the daily data you scrap on the website as well here and here for example:

https://doublexp.net/static/json/bulkmissions/2024-06-09.json

https://doublexp.net/static/json/bulkmissions/2024-06-10.json

Can I use these for a Flutter mobile application and use your pages for the data, with proper credits of course.

**Comment by rolfosian** [comment]
Sure thing, it's all going to be outdated very soon though. I've got a somewhat working version up to date with the current experimental build at https://experimental.doublexp.net/, but there are a few issues with some edge cases in season/mission configs that i *think* are handled, but the mission generator could be tweaked by gsg again at any point. I've done away with the season keys for the missions themselves and started using the `exclude_from` key exclusively to filter missions per season now, but I'm yet to put that up as I'm still monitoring the localhost version for any hiccups and the function i wrote to assign the exclusions and handle the edge cases is 200 lines long and insanely bloated and im not sure if i even trust it tbh.

You can find me at https://steamcommunity.com/id/Rolfos/ or on discord by the same name if you have any questions. The individual daily json files like the ones you linked are only split and written on [server startup](https://github.com/rolfosian/drgmissions/blob/main/flask/main.py#L70), and i have no github actions or whatever set up to host them here specifically, they're only really on the repo because of testing lol
