### ISSUE TITLE
Mission Missing

### ISSUE THREAD

**Issue by ChriStrongL** [rolfosian/drgmissions#2]
Seems that one mission is missing from doublexp.net.
The JSON is aslo missing that mission.
The third pic is just to prove that mission "exist".
Time Period: 12/13/2023 23:00~23:30 (American/NewYork)
![sc1](https://github.com/rolfosian/drgmissions/assets/46773976/54d43747-5b53-4dd5-90a9-82be75f803a2)
![sc2](https://github.com/rolfosian/drgmissions/assets/46773976/6a5242c4-f75c-4e2d-881e-99a5d661fab8)
![sc3](https://github.com/rolfosian/drgmissions/assets/46773976/2a20c510-e640-4bc9-a51f-36085670904b)
Good work btw, R&S!

**Comment by rolfosian** [comment]
This is possibly because I ran the script to scrape the metadata and make the json with the season content box unticked ingame. I see in your screenshot that the Biome in the mission terminal has the red plague overlay. Perhaps I will add a note saying that some missions may be missing as a result or something, but refactoring to handle the two different sets of data is simply something I don't feel like doing at this stage sorry. 

Theoretically it could be done without much extra time incurred for the scraping (it takes multiple hours to collate 3-4 months worth of mission data for reasons) via multiple machines running concurrently, or just an extra pass after finding the function to tick and untick the box every round, but again, I can't really be bothered doing it myself after my 2k ingame hrs of DRG and burning out on lithophage.

**Comment by ChriStrongL** [comment]
Got it. Agree that rockpox is really annoying. But I found that it will be a little difficult to search server if I untick rockpox. Seems that most of miners leave it on. So I have to tick it.
Anyway, thanks for your work.
R&S!
